apiVersion: v1
kind: Secret
metadata:
  name: network-probe-secrets
  namespace: network-probe
  labels:
    app.kubernetes.io/name: network-probe-platform
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database secrets
  POSTGRES_PASSWORD: "your_secure_postgres_password"
  
  # Redis secrets
  REDIS_PASSWORD: "your_secure_redis_password"
  
  # RabbitMQ secrets
  RABBITMQ_PASSWORD: "your_secure_rabbitmq_password"
  
  # Application secrets
  SECRET_KEY: "your-very-secure-secret-key-change-this-in-production"
  JWT_SECRET_KEY: "your-jwt-secret-key-change-this-in-production"
  
  # Email secrets
  SMTP_USER: "your-email@gmail.com"
  SMTP_PASSWORD: "your-email-password"
  
  # Agent secrets
  AGENT_TOKEN: "your-secure-agent-token"

---
apiVersion: v1
kind: Secret
metadata:
  name: network-probe-tls
  namespace: network-probe
  labels:
    app.kubernetes.io/name: network-probe-platform
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Replace with your actual certificate data
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...